[package]
name = "sol_get_balance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.14.6"
solana-sdk = "1.14.6"
solana-program = "1.14.6"
